// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::datapoint_type::Datapoint;
use super::variant_type_type::VariantType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `datapoint`.
///
/// Obtain a handle from the [`DatapointTableAccess::datapoint`] method on [`super::RemoteTables`],
/// like `ctx.db.datapoint()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.datapoint().on_insert(...)`.
pub struct DatapointTableHandle<'ctx> {
    imp: __sdk::TableHandle<Datapoint>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `datapoint`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DatapointTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DatapointTableHandle`], which mediates access to the table `datapoint`.
    fn datapoint(&self) -> DatapointTableHandle<'_>;
}

impl DatapointTableAccess for super::RemoteTables {
    fn datapoint(&self) -> DatapointTableHandle<'_> {
        DatapointTableHandle {
            imp: self.imp.get_table::<Datapoint>("datapoint"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DatapointInsertCallbackId(__sdk::CallbackId);
pub struct DatapointDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DatapointTableHandle<'ctx> {
    type Row = Datapoint;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Datapoint> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DatapointInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DatapointInsertCallbackId {
        DatapointInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DatapointInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DatapointDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DatapointDeleteCallbackId {
        DatapointDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DatapointDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Datapoint>("datapoint");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct DatapointUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DatapointTableHandle<'ctx> {
    type UpdateCallbackId = DatapointUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DatapointUpdateCallbackId {
        DatapointUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DatapointUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Datapoint>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Datapoint>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `datapoint`,
/// which allows point queries on the field of the same name
/// via the [`DatapointIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.datapoint().id().find(...)`.
pub struct DatapointIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Datapoint, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DatapointTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `datapoint`.
    pub fn id(&self) -> DatapointIdUnique<'ctx> {
        DatapointIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DatapointIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Datapoint> {
        self.imp.find(col_val)
    }
}
