// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::metadata_type::Metadata;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `metadata`.
///
/// Obtain a handle from the [`MetadataTableAccess::metadata`] method on [`super::RemoteTables`],
/// like `ctx.db.metadata()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.metadata().on_insert(...)`.
pub struct MetadataTableHandle<'ctx> {
    imp: __sdk::TableHandle<Metadata>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `metadata`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MetadataTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MetadataTableHandle`], which mediates access to the table `metadata`.
    fn metadata(&self) -> MetadataTableHandle<'_>;
}

impl MetadataTableAccess for super::RemoteTables {
    fn metadata(&self) -> MetadataTableHandle<'_> {
        MetadataTableHandle {
            imp: self.imp.get_table::<Metadata>("metadata"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MetadataInsertCallbackId(__sdk::CallbackId);
pub struct MetadataDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MetadataTableHandle<'ctx> {
    type Row = Metadata;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Metadata> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MetadataInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MetadataInsertCallbackId {
        MetadataInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MetadataInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MetadataDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MetadataDeleteCallbackId {
        MetadataDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MetadataDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Metadata>("metadata");
    _table.add_unique_constraint::<String>("path", |row| &row.path);
}
pub struct MetadataUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MetadataTableHandle<'ctx> {
    type UpdateCallbackId = MetadataUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MetadataUpdateCallbackId {
        MetadataUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MetadataUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Metadata>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Metadata>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `path` unique index on the table `metadata`,
/// which allows point queries on the field of the same name
/// via the [`MetadataPathUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.metadata().path().find(...)`.
pub struct MetadataPathUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Metadata, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MetadataTableHandle<'ctx> {
    /// Get a handle on the `path` unique index on the table `metadata`.
    pub fn path(&self) -> MetadataPathUnique<'ctx> {
        MetadataPathUnique {
            imp: self.imp.get_unique_constraint::<String>("path"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MetadataPathUnique<'ctx> {
    /// Find the subscribed row whose `path` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Metadata> {
        self.imp.find(col_val)
    }
}
