// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterDatapointArgs {
    pub path: String,
}

impl From<RegisterDatapointArgs> for super::Reducer {
    fn from(args: RegisterDatapointArgs) -> Self {
        Self::RegisterDatapoint { path: args.path }
    }
}

impl __sdk::InModule for RegisterDatapointArgs {
    type Module = super::RemoteModule;
}

pub struct RegisterDatapointCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_datapoint`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_datapoint {
    /// Request that the remote module invoke the reducer `register_datapoint` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_register_datapoint`] callbacks.
    fn register_datapoint(&self, path: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `register_datapoint`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RegisterDatapointCallbackId`] can be passed to [`Self::remove_on_register_datapoint`]
    /// to cancel the callback.
    fn on_register_datapoint(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> RegisterDatapointCallbackId;
    /// Cancel a callback previously registered by [`Self::on_register_datapoint`],
    /// causing it not to run in the future.
    fn remove_on_register_datapoint(&self, callback: RegisterDatapointCallbackId);
}

impl register_datapoint for super::RemoteReducers {
    fn register_datapoint(&self, path: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("register_datapoint", RegisterDatapointArgs { path })
    }
    fn on_register_datapoint(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> RegisterDatapointCallbackId {
        RegisterDatapointCallbackId(self.imp.on_reducer(
            "register_datapoint",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RegisterDatapoint { path },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, path)
            }),
        ))
    }
    fn remove_on_register_datapoint(&self, callback: RegisterDatapointCallbackId) {
        self.imp.remove_on_reducer("register_datapoint", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `register_datapoint`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_register_datapoint {
    /// Set the call-reducer flags for the reducer `register_datapoint` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn register_datapoint(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_register_datapoint for super::SetReducerFlags {
    fn register_datapoint(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("register_datapoint", flags);
    }
}
