// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::variant_type_type::VariantType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetDatapointValueArgs {
    pub id: u32,
    pub value: VariantType,
}

impl From<SetDatapointValueArgs> for super::Reducer {
    fn from(args: SetDatapointValueArgs) -> Self {
        Self::SetDatapointValue {
            id: args.id,
            value: args.value,
        }
    }
}

impl __sdk::InModule for SetDatapointValueArgs {
    type Module = super::RemoteModule;
}

pub struct SetDatapointValueCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_datapoint_value`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_datapoint_value {
    /// Request that the remote module invoke the reducer `set_datapoint_value` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_datapoint_value`] callbacks.
    fn set_datapoint_value(&self, id: u32, value: VariantType) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_datapoint_value`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetDatapointValueCallbackId`] can be passed to [`Self::remove_on_set_datapoint_value`]
    /// to cancel the callback.
    fn on_set_datapoint_value(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32, &VariantType) + Send + 'static,
    ) -> SetDatapointValueCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_datapoint_value`],
    /// causing it not to run in the future.
    fn remove_on_set_datapoint_value(&self, callback: SetDatapointValueCallbackId);
}

impl set_datapoint_value for super::RemoteReducers {
    fn set_datapoint_value(&self, id: u32, value: VariantType) -> __sdk::Result<()> {
        self.imp
            .call_reducer("set_datapoint_value", SetDatapointValueArgs { id, value })
    }
    fn on_set_datapoint_value(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32, &VariantType) + Send + 'static,
    ) -> SetDatapointValueCallbackId {
        SetDatapointValueCallbackId(self.imp.on_reducer(
            "set_datapoint_value",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetDatapointValue { id, value },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, value)
            }),
        ))
    }
    fn remove_on_set_datapoint_value(&self, callback: SetDatapointValueCallbackId) {
        self.imp
            .remove_on_reducer("set_datapoint_value", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_datapoint_value`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_datapoint_value {
    /// Set the call-reducer flags for the reducer `set_datapoint_value` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_datapoint_value(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_datapoint_value for super::SetReducerFlags {
    fn set_datapoint_value(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("set_datapoint_value", flags);
    }
}
