// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum VariantType {
    I32(i32),

    I64(i64),

    U32(u32),

    U64(u64),

    Float(f32),

    Double(f64),

    Bool(bool),

    String(String),
}

impl __sdk::InModule for VariantType {
    type Module = super::RemoteModule;
}
